### ISSUE TITLE
Mandatory Special Count

### ISSUE THREAD

**Issue by b3brodie** [chaosvolt/cdda-fewer-farms-mod#1]
With one of the changes to map specials in experimental: https://github.com/CleverRaven/Cataclysm-DDA/pull/46701, the fewer farms mod seems to add a very large amount of mandatory special locations to the game.  With just the base game and this mod there is no issue, but by adding a couple of other mods that also add mandatory specials it quickly goes over the limit (72) for mandatory specials.  I don't have the exact numbers, but fewer farms at minimum adds 12+ mandatory special areas based on the presence and lack of presence of the error (overmap.cpp line 426).

**Comment by chaosvolt** [comment]
It might be something fucky with how it treats unique specials I'm guessing, going back to occurrences of 0-1 should fix it. One sec.

**Comment by chaosvolt** [comment]
That should do it, but do tell me if anything else crops up.
